### ISSUE TITLE
How i get the pre_logits of the model to use it as backbone

### ISSUE THREAD

**Issue by StephanElter** [sayakpaul/ViT-jax2tf#4]
Hi sayakpaul,
nice work!
I want use the Model as backbone without MLP. First i thought i get it with the feature model but i notice the output is only the CLS token. ?
How i get the pre_logits of the ViT in your Models?
i mean...  how get i the output of all token = cls +  for all patch ((224/16) ^2) of the ViT-model

regards, Stephan

**Comment by sayakpaul** [comment]
Use these models: https://github.com/sayakpaul/ViT-jax2tf#feature-extractors.

**Comment by StephanElter** [comment]
Thanks Paul, for the quick answer

but I am at the same point before. As i wrote i used the  
feature-extractor model, but
The output of this layer are only one token. I guess it is the CLS token.
Sorry 'pre_logits' was the wrong naming. I mean the output of the  
Encoder-Block.
I want use this for semantic segmentation like in  
https://github.com/rstrudel/segmenter
I search a model with all token as output.

The shape would be (None, 197, 384)
384 is the dimensionallity of one token (see ViT-S)

Table 1: Configurations of ViT models.
Model Layers Width MLP Heads Params
ViT-Ti [34] 12 192 768 3 5.8M
ViT-S [34] 12 384 1536 6 22.2M
ViT-B [10] 12 768 3072 12 86M
ViT-L [10] 24 1024 4096 16 307M

The shape of your feature-extractor model is:

Model: "sequential"
_________________________________________________________________
  Layer (type)                Output Shape              Param #
=================================================================
  keras_layer (KerasLayer)    (None, 384)               21665664

  dense (Dense)               (None, 5)                 1925

=================================================================
Total params: 21,667,589
Trainable params: 21,667,589
Non-trainable params: 0
_________________________________________________________________

**Comment by sayakpaul** [comment]
Oh I see now. That you won't get from the TensorFlow Hub models I mentioned since they are packed as one single concrete function. 

If you want to do this in TensorFlow and Keras, then you might have to first write Vision Transformer class and then populate the original weights into that. An example is here: https://github.com/sayakpaul/BiT-jax2tf.
